### ISSUE TITLE
count getting error On windows

### ISSUE THREAD

**Issue by inspiring71** [krewx/mssql-sailsv1#1]
when using along with sails 1.1, for count() function without any argument I get this error  Incorrect syntax near 'WHERE'

the solution I found:
change serializeOptions function in sql.js like this:
	serializeOptions: function(collectionName, options) {

		var queryPart = '';
		if (options.where && Object.keys(options.where).length) {
			queryPart += ' WHERE ' + sql.where(collectionName, options.where) + ' ';
		}

**Comment by krewx** [comment]
Thanks let me check it.
