### ISSUE TITLE
populate error

### ISSUE THREAD

**Issue by inspiring71** [krewx/mssql-sailsv1#2]
when I try to use populate on one-to-many relationship, I get a warning and instead of one record, I get an array of on record.
I tried to solve it but I could not find any solution yet. I will post the solution if I found any.
thank you for your great adapter:-)

**Comment by inspiring71** [comment]
I found a workaround for this problem, but it is just nasty. I post it here in case it gives you the idea for solving it with cleaner solutions:
in adapter.js change line 400 like this:
 if(cb.toString().indexOf("afterFetchingBufferRecords")!=-1){
            cb(undefined, recordset.recordset[0]);              
          }else{
            cb(undefined, recordset.recordset);
          }


.\node_modules\waterline-cursor\cursor\cursor.js replace line 100 with this:
      if (buffer.records && buffer.records.length) {
        matchingParentRecord[buffer.keyName] = buffer.records;
      } else if(_.isObject(buffer.records) && Object.keys(buffer.records).length){
        matchingParentRecord[buffer.keyName] = buffer.records;
      }else{
        matchingParentRecord[buffer.keyName] = null;
      }

Hope it becomes useful for further debugging

**Comment by krewx** [comment]
Hi @inspiring71 thanks for the proposal, I just have one question with your issue, the property in the model you are populating its a collection?

**Comment by krewx** [comment]
Hi @inspiring71 sorry for not using your proposal but I don't have access to the code of waterline-cursor but I found a workaround jejeje so please just update the version of the package to the 0.0.3 in your package.json and this should be fixed. Thanks for using the adapter. If you find more issues, keep opening posts.

**Comment by inspiring71** [comment]
seem like the problem is still in place. could you recheck it, since I still get a warning about it. I use source model as an association for user model.
thanks for the support:-)

**Comment by inspiring71** [comment]
to demonstrate the problem better instead of : 
```
{
  "status": "success",
  "total_pages": 2,
  "current_page": 1,
  "users": [
    {
      "createdAt": "1551822210",
      "updatedAt": "1551958484482",
      "id": 1,
      "source": 
        {
          "createdAt": "1551821557",
          "updatedAt": "1551821557",
          "id": 1,
          "name": "default site",
          "ip": "127.0.0.1"
        }
      
    }
  ]
} 
```
I  get:
```
{
  "status": "success",
  "total_pages": 2,
  "current_page": 1,
  "users": [
    {
      "createdAt": "1551822210",
      "updatedAt": "1551958484482",
      "id": 1,
      "source": [
        {
          "createdAt": "1551821557",
          "updatedAt": "1551821557",
          "id": 1,
          "name": "default site",
          "ip": "127.0.0.1"
        }
      ]
    }
  ]
}
```
As you see, source is an array instead of an object and it throws a warning.
